# Generated by Django 3.2.4 on 2021-06-30 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '版块',
                'verbose_name_plural': '版块',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('text', models.TextField(verbose_name='正文')),
                ('agree_count', models.IntegerField(default=0, verbose_name='赞同量')),
                ('disagree_count', models.IntegerField(default=0, verbose_name='反对量')),
                ('views_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('comments_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布日期')),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='编辑日期')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.part', verbose_name='所属版块')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='内容')),
                ('agree', models.IntegerField(default=0, verbose_name='赞同')),
                ('disagree', models.IntegerField(default=0, verbose_name='反对')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='帖子')),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment', verbose_name='子评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
