# Generated by Django 3.2.4 on 2021-06-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='examine',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Pass'), (3, 'Reject')], default=1, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=20, verbose_name='版块'),
        ),
    ]
