# Generated by Django 3.2.4 on 2021-06-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210630_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='examine',
            field=models.IntegerField(choices=[(1, 'Waiting'), (2, 'Pass'), (3, 'Reject')], default=1, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='被删除？'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='被删除？'),
        ),
    ]
